#!/usr/bin/env bash
#  Copyright 2015 Daniel Giribet <dani - calidos.cat>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
echo '*** Building and packaging Mesos, this will take a long time ****'
if [ -e '/usr/lib/jvm/java' ]; then
	# open jdk
	export JAVA_HOME='/usr/lib/jvm/java'
else
	# oracle
	export JAVA_HOME='/usr/lib/jvm/java-8-oracle'
fi
M2_HOME=`pwd`/.deps/apache-maven \
	MAVEN_HOME=$M2_HOME \
	PATH=$MAVEN_HOME/bin:$PATH \
	MVN=$MAVEN_HOME/bin/mvn \
		.deps/apache-maven/bin/mvn -q package
echo '*** Finished building and packaging Mesos ****'
